# Generated by Django 2.2.13 on 2020-07-01 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city_name', models.CharField(max_length=100)),
                ('popularity_rate', models.FloatField(null=True)),
                ('average_satisfaction_rate', models.FloatField(null=True)),
                ('total_reviews', models.BigIntegerField(null=True)),
                ('uidentifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('uidentifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_popularity_rate', models.FloatField(null=True)),
                ('average_satisfaction_rate', models.FloatField(null=True)),
                ('average_price', models.IntegerField(null=True)),
                ('total_reviews', models.BigIntegerField(null=True)),
                ('restaurants', models.ManyToManyField(to='delectatech.Restaurant')),
            ],
        ),
    ]
