# Generated by Django 2.2.13 on 2020-07-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delectatech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='average_satisfaction_rate',
            new_name='satisfaction_rate',
        ),
    ]
