# Generated by Django 2.2.13 on 2020-07-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delectatech', '0002_auto_20200701_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='average_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='average_price',
            field=models.FloatField(null=True),
        ),
    ]
