# Generated by Django 2.2.13 on 2020-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delectatech', '0003_auto_20200701_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='street_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
